- .github/workflows/release.yml
- .goreleaser.yml
The release binaries for GitHub are not built as part of the release process. This means they need to be compiled on a developer machine, which isn't ideal. Using GitHub Actions we can automate this process with a single workflow (+ goreleaser).
This PRs adds a workflow to GitHub Actions that will build the binaries when a release is created. This will include a windows and linux release (for amd64), with a checksums file. [GoReleaser](https://goreleaser.com/) handles the compilation and deployment to github.
This was tested with my local fork (jrbeverly/bmx), which works really well for prototyping ideas without needing a TravisCI account.
> Support automated releases using GitHub Actions

- .github/workflows/main.yml
This PR adds in Coveralls with GitHub Actions, removing the remaining dependency on TravisCI. You'll see it along with the checks for a pull request, with it reporting the code coverage amount.
After this I'll raise a PR that completes the process of deprecating TravisCI. Additionally I ran a format on the yml file, which change the other files.
> Configure Coveralls in GitHub Actions

- .coveralls.yml
- .github/workflows/main.yml
- README.md
While implementing the GitHub Actions work, I noticed that coveralls seems to fail often. I suspect this is a requirement (or setting) that enforces code coverage of changes. However it is throwing failures even in the case of document / build harness changes.
This PR removes coveralls and all mentions of it from the repository. 
If at a later date we reconfigure this (or have a strategy for this), we can revert this commit to re-implement.
> Remove Coveralls from the repository

- cmd/bmx/print.go
- print.go
- print_test.go
- print_unix.go
- print_windows.go
At the moment the `bmx print` command assumes a 1-to-1 relation for the shell and operating system. This can be an issue when you are working with powershell in linux, or bash on windows. To resolve this, this PR adds support for an output option to control the shell command output.
This PR adds support for the command option `--output=[bash|powershell]` that determines the output command. The default output of the command is determined by the OS (linux=bash, windows=powershell), with the `--output` command.
Additionally, the `bmx.Print` function has been changed to emit the command, then print.
Resolves #187
> Allow specifying the output format from the command line

- Bmx.Core/BmxCore.cs
- Bmx.Core/IIdentityProvider.cs
- Bmx.Idp.Okta/OktaClient.cs
Partly closes #194 
This one is especially nasty. As mentioned in the issue, the "only" way to currently get SAML from Okta to use in order to auth against AWS (as well as to figure out the roles), is to parse an Okta provided webpage (its the same one where you choose which role you want to sign into AWS account as in browsers).
I've decided to break into two tasks: 
1. Okta IDP Service is only gonna to extract the SAML data
2. AWS Service will parse the SAML for Roles in the account as well  as exchange for tokens from STS. 
This PR addresses the first part
It's a bit of https://stackoverflow.com/a/1732454/4433646 :(
> Get AWS SAML Credentials from Okta

- Bmx.CommandLine/CommandLine.cs
- Bmx.Core/BmxCore.cs
- Bmx.Core/ICloudProvider.cs
- Bmx.Core/IIdentityProvider.cs
- Bmx.Idp.Okta/OktaClient.cs
- Bmx.Service.Aws/AwsClient.cs
- Bmx.Service.Aws/Models/AwsRole.cs
closes #194 
Add Cloud Provider (in this case AWS) which exchanges Okta provided SAML for short lived AWS tokens (these are what BMX outputs). 
- Parse out SAML from okta to Identify roles in the account,
- Use AWS SDK for .NET to Assume a role via the SAML
> Exchange AWS SAML from Okta for AWS Access Tokens via STS

- Bmx.CommandLine/Bmx.CommandLine.csproj
- Bmx.CommandLine/CommandLine.cs
- Bmx.CommandLine/IBmxConfig.cs
- Bmx.CommandLine/IniConfiguration.cs
- Bmx.CommandLine/Program.cs
Closes #201 
Did some odd stuff for merging values for runtime args to values found in configs, System.CommandLine doesn't have a good solution for this [at the moment](https://github.com/dotnet/command-line-api/issues/857).
Aside:
That lib has a lot of in-draft/wip features so I think it makes sense to do some things manually for now.
> Implement loading args from config

- Bmx.CommandLine/CommandLine.cs
- Bmx.CommandLine/IniConfiguration.cs
- Bmx.CommandLine/Program.cs
- Bmx.Core/BmxCore.cs
- Bmx.Core/Events.cs
- Bmx.Core/IBmxCore.cs
- Bmx.Core/ICloudProvider.cs
- Bmx.Core/IIdentityProvider.cs
- Bmx.Core/State/IAccountState.cs
- Bmx.Core/State/IAuthenticateState.cs
- Bmx.Core/State/IAuthenticatedState.cs
- Bmx.Core/State/IRoleState.cs
- Bmx.Idp.Okta/OktaClient.cs
- Bmx.Idp.Okta/State/OktaAccountState.cs
- Bmx.Idp.Okta/State/OktaAuthenticateState.cs
- Bmx.Idp.Okta/State/OktaAuthenticatedState.cs
- Bmx.Service.Aws/AwsClient.cs
- Bmx.Service.Aws/State/AwsRoleState.cs
More of an experimental thing, if it looks too silly / convoluted please feel free to say so, its not essential that it's merged.
BMX is primarily about talking to Okta (beyond a generic interface of course). The Okta Authentication API is stateful with for example a state token during authentication which is then exchanged for a session token. 
Its easy enough to store this state internally to OktaIdentityProvider without leaking implementation data to BMXCore (the project that orchestrates the various calls to Identity and Cloud Providers. [Workflow diagram](https://github.com/Brightspace/bmx/wiki/Architecture).
What this means though is that for example Identity Service has very strong sequential coupling, calls cannot be called out of order or skipped. Which is a code smell + it makes …
> Refactor Identity and Cloud provider services to be stateless.

- saml/identityProviders/okta/okta.go
This causes bmx to print the user password when Okta returns invalid responses.
> don't print request body on error

- src/D2L.Bmx/Authenticate.cs
- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/Print.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/Write.cs
Recreates the base CLI using dotnet. Does not yet read from config files.
To run the CLI, use the BMX commands as usual, except replace `bmx` with `dotnet run -- `
Ex. `bmx print --org d2l` becomes `dotnet run -- print --org d2l`
> dotnet7: Recreate dotnet cli

- Directory.Build.props
- src/D2L.Bmx/Authenticate.cs
- src/D2L.Bmx/Print.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/Write.cs
We use Roslynator analyzers in all our team's C# codebase and have some rules (already defined in .editorconfig) we enforce at build time.
Noticed that bmx didn't have them.
> add Roslynator and fix nonconformance

- .github/workflows/format.yml
There was a typo in the format workflow that caused it to fail
> Fixing format workflow

- src/D2L.Bmx/Authenticate.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/PrintHandler.cs
- src/D2L.Bmx/WriteHandler.cs
Removes redundant naming of Okta API methods
> Remove Okta from method names

- src/D2L.Bmx/Authenticate.cs
- src/D2L.Bmx/Okta/Models/OktaMeResponse.cs
- src/D2L.Bmx/Okta/Models/OktaSessionCache.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/Okta/OktaSessionStorage.cs
- src/D2L.Bmx/Okta/SourceGenerationContext.cs
- src/D2L.Bmx/Okta/State/OktaAuthenticatedState.cs
Currently we need to type our okta password in every time. Go version supported caching a session id and reusing it until expiry
Related trello card: https://trello.com/c/GGgGonzC/1216-support-storing-session-and-profiles
> cache okta sessions

- .github/workflows/publish.yml
Seeing some Docker builds timeout. Looks like ubuntu.com may be slow today.
https://github.com/Brightspace/bmx/actions/runs/4982545341/jobs/8918545588
No reason to give a shorter 5-minute timeout to the Docker builds when the non-containerized builds have a timeout of 10 minutes.
> longer docker builds timeout

- src/D2L.Bmx/Authenticate.cs
- Skip MFAoption selection if only 1 option is available.
> choose MFA option if there is only one

- .github/workflows/publish.yml
Creating a drafted release doesn't set the tag as what our input is. It's of some format untagged-xxxxxxxxxx . So we need to extract that value from when we create the release and then pass that to remaining steps when uploading.
Also need a new step for removing the draft flag once all the builds have been uploaded.
We're adding a new input for the dispatch called `prerelease`. This will set the created release as a prerelease so we can test the entire workflow without updating the `latest` release tag
> ci: publish workflow uses draft tag id and finalizes release

- .github/workflows/publish.yml
The prerelease input was one tab off and not under `inputs`. Oops
> ci: publish indent prerelease

- src/D2L.Bmx/ConfigureHandler.cs
- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/Okta/OktaAuthenticator.cs
- src/D2L.Bmx/Okta/OktaSessionStorage.cs
- src/D2L.Bmx/PrintHandler.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/WriteHandler.cs
Code that directly interacts with external systems should generally be put behind interfaces and not be in static classes/methods. This is necessary to have any sort of unit tests. The .NET bmx doesn't have unit tests right now, but we should still follow this general principle as a best practice.
Main changes:
* Consolidate all user console prompts into `ConsolePrompter` and put it behind an interface.
* Write all console prompts to stderr instead of stdout to make `bmx print` usable.
* Put `OktaSessionStorage` behind an interface too
* Rename `Authenticator` to `OktaAuthenticator` and move it to the Okta namespace
Note: I'm not putting all classes behind interfaces (e.g. `OktaAuthenticator`). Even when we want to unit test the code, code that doesn't directly interact with external …
> make classes non-static where appropriate

- src/D2L.Bmx/Aws/AwsClient.cs
- src/D2L.Bmx/PrintHandler.cs
there's (almost) no reason to do ugly string escaping when C# 11 has the excellent [raw string literal][1] feature.
[1]: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/raw-string-literal
> clean up print output by using raw string literals

- src/D2L.Bmx/BmxConfigProvider.cs
First time users will crash on finishing `bmx configure` command because the .bmx folder and config file does not exist
> configure: create .bmx folder and config file if needed

- Dockerfile.alpine
- Dockerfile.ubuntu
The SDK is complaining
https://github.com/Brightspace/bmx/actions/runs/5061042812/jobs/9086405178?pr=307#step:4:521
We can't output a solution because it may contain multiple projects. It isn't currently erroring because there's only one project in the solution, but it will once we add another project (e.g. tests).
> specify project path when building inside Docker

- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/Okta/Models/AuthenticateChallengeMfaOptions.cs
- src/D2L.Bmx/Okta/Models/AuthenticateRequest.cs
- src/D2L.Bmx/Okta/Models/AuthenticateResponse.cs
- src/D2L.Bmx/Okta/Models/CreateSessionRequest.cs
- src/D2L.Bmx/Okta/Models/IssueMfaChallengeRequest.cs
- src/D2L.Bmx/Okta/Models/Readme.md
- src/D2L.Bmx/Okta/Models/VerifyMfaChallengeResponseRequest.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/Okta/State/OktaAuthenticateState.cs
- src/D2L.Bmx/Okta/State/OktaAuthenticatedState.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/SourceGenerationContext.cs
* Remove bloat
We have both `OktaAuthenticateState` and `OktaAuthenticatedState`... wut
* Simplify method signature and use better method/type names around Okta authentication API
There're many `FooOptions` types that can be confusing when there's also the [options pattern][1] in .NET. Calling these types `FooRequest` is more in line with our convention.
* Better handle polymorphic responses from authentication API calls to give more accurate type (including nullability) info and helps clarify caller logic
[1]: https://learn.microsoft.com/en-us/dotnet/core/extensions/options
> refactor/clean up Okta authn code

- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/Okta/OktaSessionStorage.cs
- src/D2L.Bmx/OktaAuthenticator.cs
Currently the .NET bmx will create the ~/.bmx directory and an empty session file when the user doesn't have anything configured, which is a weird behaviour.
Creating directory and file should be in the `SaveSessions` method. BMX should leave no trace if the user doesn't configure anything.
> Don't create session file on read

- .github/workflows/publish.yml
- Dockerfile.alpine
- Dockerfile.ubuntu
- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/nuget.config
The biggest the motivation for the change is to enable [invariant globalization mode][1].
The default Alpine image doesn't have an ICU library, so the previous bmx Alpine binaries can't run on a clean Alpine container. Enabling invariant globalization removes the ICU dependency, which makes bmx run well on Alpine, and reduces the binary size a bit, too.
[1]: https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md
> update build configuration

- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/ILLink.Descriptors.xml
To safely enable full trim mode and produce smaller executables.
For Windows executables, it brings the size down from 15.95 MiB to 12.62 MiB (~20% reduction).
> selectively preserve AWSSDK types from trimming

- src/D2L.Bmx/BmxConfig.cs
- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/ConfigureHandler.cs
- src/D2L.Bmx/ConsolePrompter.cs
Slack discussion [here](https://d2l.slack.com/archives/G4P099831/p1685471844688699)
tldr: This feature came in the Go version without previously being in V1 and guessing we left it as an experimental flag. Partly because it could crash on Linux systems working its way up the directories. This isn't a problem now in .NET version. 
This feature has matured enough to become a default setting. So now we will simply always look for a .bmx file in the CWD.
> remove allow_project_configs config option

- .dockerignore
- .gitignore
- src/D2L.Bmx/ConsolePrompter.cs
If we only turn off input echoing, a user pressing Ctrl+C while entering password in a `$(bmx print)` will stop BMX and have their terminal display "crippled" - input echoing still off.
To resolve this issue, use raw mode in the terminal and receive all key strokes, and handle Ctrl+C behaviour ourselves.
This also largely unifies the password input processing logic across both Windows & *nix platforms.
> control all key strokes when entering password

- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/BmxPaths.cs
To ensure that project config file lookup won't crash the app or get it stuck.
Related discussion: https://d2l.slack.com/archives/G4P099831/p1685471844688699
[Hide whitespace changes](https://github.com/Brightspace/bmx/pull/326/files?w=1)
> limit max search depth for project config file

- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/Properties/launchSettings.json
- src/D2L.Bmx/WriteHandler.cs
The `SharedCredentialsFile` has a good implementation for working with ini files but the output is that of `x=y`. The GO version of BMX had the output such that every `=` sign for each line was aligned. 
Use a third party ini parser library that will let us update / create profiles. The libraries I looked through don't have this same feature for dotnet. 
I considered writing something custom to give us the same kind of output here. While I got that working, I was worried of edge cases where the time spent wouldn't be worth it. Last thing I want is to break someone's credentials file.
So the new output will be in the format `x = y` instead of `x=y`
> write: use ini parser to format credentials file

- .github/workflows/publish.yml
- src/D2L.Bmx/D2L.Bmx.csproj
Add version Number format check
Make bmx --version work
> Github Action: Add version and version format check.

- src/D2L.Bmx/Program.cs
Distinction between different uses of `--output` was not obvious.
> rename `--output` to `--format` for print command

- src/D2L.Bmx/ConsolePrompter.cs
`--save` isn't in the POSIX spec, and Mac doesn't implement it, so output is messed up after password input.
Switch to `-g` which is equivalent and defined in POSIX.
See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/stty.html
Related discussion: https://d2l.slack.com/archives/G4P099831/p1687794940963309
> use POSIX compliant stty arguments

- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/ConfigureHandler.cs
- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/Program.cs
Currently configure command will overwrite all existing settings in the config file
We can use an ini parser the same way we do for `bmx write` and not do a complete rewrite of the file. This requires us to change some of the console prompter code as it currently will throw an exception if no input is given
Related trello card [here](https://trello.com/c/VFHzMaY4/1295-configure-command-should-keep-existing-entries-in-the-config-file)
> configure: prevent data stomping

- src/D2L.Bmx/WriteHandler.cs
Parser defaults to UTF-8-BOM and credentials file needs to be UTF-8. Current version of write will cause aws cli to give error about how it can't parse the credentials file
> write: fix ini parser encoding to UTF-8

- .github/workflows/publish.yml
In the future we'll likely want to add ARM builds, and it'd be good to not break the naming pattern (and existing automated processes) when we do.
> CI: include CPU arch in release assets names

- .github/workflows/publish.yml
- Dockerfile.alpine
- Dockerfile.ubuntu
We forgot to do this for the docker builds
> ci: docker builds set their build version

- src/D2L.Bmx/PrintHandler.cs
Currently `bmx print` doesn't work in Git Bash.
> force LF as newline when printing bash commands

- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/D2L.Bmx.csproj
IniParser and Microsoft.Extensions.Configuration.Ini have roughly the same functionalities. Using Iniparser only to make code more consistent
> Use ini-parser-netstandard for all ini file parsing

- src/D2L.Bmx/BmxPaths.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/SourceGenerationContext.cs
- src/D2L.Bmx/UpdateChecker.cs
Helps users know we have a new version out. This is a middle step in terms of having an update feature. It'd be good to keep all our users on the latest version.
We will ping github once every 24 hours and save the version tag it returned. So currently if there is a new version the user will see it every time they run BMX. I could change that to once every 24 hours though but this also maybe annoys them enough to want to upgrade lol
If the org is d2l we prompt them to visit out site with the install script. Users outside of d2l will get prompted to visit the github repo
related trello card: https://trello.com/b/r6wdvBry/vulcan-project-board
slack discussion: https://d2l.slack.com/archives/G4NV94H2A/p1693323866881979
> check for updates on run

- src/D2L.Bmx/UpdateChecker.cs
Shorter timeout so people don't have to wait as long
> update checker: reduce timetout to 2 seconds and trim tag name

- src/D2L.Bmx/Aws/AwsClient.cs
- src/D2L.Bmx/BmxException.cs
- src/D2L.Bmx/Okta/OktaApi.cs
Adding more error handling to network calls to avoid the general "BMX exited with unexpected internal error" error.
> Okta and AWS broader error handling

- .github/labeler.yml
Brightspace/third-party-actions@actions/labeler is [updated][1] to actions/labeler@v5 with [breaking changes][2].
[1]: https://github.com/Brightspace/third-party-actions-config/pull/1101
[2]: https://github.com/actions/labeler?tab=readme-ov-file#breaking-changes-in-v5
> Update labeler.yml for actions/labeler@v5

- src/D2L.Bmx/BmxPaths.cs
- src/D2L.Bmx/GithubRelease.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/UpdateChecker.cs
- src/D2L.Bmx/UpdateHandler.cs
Need a command to update bmx with a new version if one is available
> Adding update command

- src/D2L.Bmx/BmxPaths.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/UpdateChecker.cs
- src/D2L.Bmx/UpdateHandler.cs
Partly code refactor/nits, partly behavioural changes:
* Use `~/.bmx/temp` exclusively as a scratch space and don't use system temp folder. Rationale is that we have cleanup logic for the former, but not the latter.
* Each BMX run uses an exclusive subdirectory under `~/.bmx/temp` to avoid any conflicts, even if cleanup fails
* Respects the filename of the currently running BMX executable during self-update
* The message from auto update check now directs users to run `bmx update` instead of going to GitHub or bmx.d2l.dev
* Print informational messages to console during the update process
> tweak update check & self-update

- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/UpdateChecker.cs
- src/D2L.Bmx/UpdateHandler.cs
- src/D2L.Bmx/VersionProvider.cs
This should rarely if ever happen for regular users, but...
if someone was using a preview release (later than "latest") and ran "bmx update", they would've seen something like:
> You already have the latest version 3.0.0.0
Problems:
* "3.0.0.0" is the "latest" release as indicated by GitHub, not the actual version the user is using, which should look like "3.1.0-preview"
* We never display the four part version format anywhere else.
This change makes this message displays the actual version the user currently has, and uses the "informational version" to align with what users would see with "bmx --version".
> display current version more accurately

- src/D2L.Bmx/AwsCredsCreator.cs
In my testing, I find the strict behaviour when using `--cache` to be counter intuitive and unnecessarily harsh.
It also makes extending code more difficult.
More here: https://github.com/Brightspace/bmx/pull/442#discussion_r1452696462
> allow interactive prompts when using cached creds

- src/D2L.Bmx/AwsCredsCreator.cs
- src/D2L.Bmx/ParameterDescriptions.cs
- src/D2L.Bmx/PrintHandler.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/WriteHandler.cs
Make it easier for people to start using BMX in `credential_process`, and reduce user errors.
https://d2l.slack.com/archives/G4P099831/p1705333949277619
> add '--use-credential-process' to write command

- src/D2L.Bmx/WriteHandler.cs
If there's a profile with the same name in the credentials and config file, it will default to the credentials file, so you will eventually get invalid credentials
https://desire2learn.atlassian.net/browse/VUL-329
> wipes profile section when bmx write --use-credential-process is ran

- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/ParameterDescriptions.cs
Potential for the config file to have bad user / org values and it's not immediately obvious to the user that those could be the reason for their okta auth failing. This can happen with our internal install script when running wsl and the user gets set to 'root' in the config file.
VUL-330
> display okta user and org in password prompt / failed auth error message

- src/D2L.Bmx/WriteHandler.cs
@cfbao noticed that the various AWS SDK's handle invoking applications used by credential_process differently. In the case of the Go SDK that includes, invoking BMX verbatim, including qoutes and all.
There isn't a need to quote any of these fields to handle white spaces (username, okta subdomain, aws role name, or assume duration etc...)
> Remove qoutes from invoke via AWS Credential Process

- src/D2L.Bmx/WriteHandler.cs
Default credentials file takes priority over the default config which is where we store profiles using `credential_process`. If someone had an existing profile in config file and then runs `bmx write`, creds will be stored into the default credentials file making the existing one useless. We should remove the existing key in the config file so there is no confusion.
`credential_process` is the better way for majority of people but there are some scenarios where it's not supported. So we are leaving some information to the user that it is no longer being used. Just in case they unintentionally ran write without the flag. Not going with a prompt to confirm because that could break existing scripts
VUL-385
> write: update config file section with same name if no cred process flag

- src/D2L.Bmx/WriteHandler.cs
follow up to this comment: https://github.com/Brightspace/bmx/pull/453#discussion_r1642971687
> refactor ini file handling logic for write command

- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/JsonSerializerContext.cs
- src/D2L.Bmx/Okta/Models/AuthenticateResponse.cs
- src/D2L.Bmx/OktaAuthenticator.cs
With .NET 9 we can use properties aside from the first in JSON to do type discrimination (in this case using ``factorType`` in the API).
So we can use it de-serialize the different properties in Factor's Profile section (in this case we only care about QuestionText for the Security Question factor).
N/A
> De-serialize Security Question MFA to different type

- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/D2L.Bmx.csproj
- src/D2L.Bmx/JsonSerializerContext.cs
- src/D2L.Bmx/Okta/Models/AuthenticateResponse.cs
- src/D2L.Bmx/OktaAuthenticator.cs
This MFA factor (which incidentally I thought we didn't allow with D2L's Okta) looked like:
```
Okta org short name or domain name: dev-1234.oktapreview.com
Okta username: awijayathilaka
Okta password: *******************
MFA Required
[1] OKTA-question
[2] GOOGLE-token:software:totp
Select an available MFA option: 1
Answer: <answer in plain text>
Successfully logged in and Okta session has been cached.
```
Now, it will mask the input for the security question (which is a static value) + prompt with the question text rather than "Answer:"
```
Okta org short name or domain name: dev-1234.oktapreview.com
Okta username: awijayathilaka
Okta password: *******************
MFA Required
[1] OKTA-question
[2] GOOGLE-token:software:totp
Select an available MFA option: 1
What is your favorite …
```
> Improve question MFA prompt

- src/D2L.Bmx/WriteHandler.cs
An AWS profile can only have one credential provider configured.
Not removing other credential providers' settings when `bmx write` runs could lead to a broken or at least confusing AWS profile.
https://desire2learn.atlassian.net/browse/VUL-402
> remove AWS credential provider settings on `bmx write`

- .github/workflows/format.yml
- .github/workflows/publish.yml
- Dockerfile.al2
- Dockerfile.alpine
- src/D2L.Bmx/D2L.Bmx.csproj
The trimmer seems to have trouble preserving the correct type when we reference a package that provides types included in the runtime.
Specifically, we're using [a System.Text.Json preview package](https://www.nuget.org/packages/System.Text.Json/9.0.0-preview.5.24306.7) to utilize the new `AllowOutOfOrderMetadataProperties` feature, but the trimmer isn't keeping relevant new members in Json Serialization types (even if explicitly instructed to by a trimmer root descriptor file), resulting in runtime errors.
Updating to .NET 9 solves this problem, as we no longer need the preview package, and the types/members we need are in the runtime.
This is likely a trimmer bug that we should report to https://github.com/dotnet/runtime/issues.
https://desire2learn.atlassian.net/browse/VUL-403
> update to .NET 9

- src/D2L.Bmx/AwsCredsCreator.cs
- src/D2L.Bmx/ConsolePrompter.cs
- src/D2L.Bmx/ConsoleWriter.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/ParameterDescriptions.cs
- src/D2L.Bmx/ParameterSource.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/WriteHandler.cs
Follow up to https://github.com/Brightspace/bmx/pull/463
As per Zoom discussion, BMX will always print parameter value & source if and only if it's provided via CLI args or config file.
I also made it colourful for legibility. The line seems too long and crowded without these colours.
The colours don't work if stdout is redirected, which is typical when using `bmx print`. I know why this is happening. Will try to fix in a separate PR.
> print parameter value if and only if provided via CLI arg or config

- src/D2L.Bmx/ConsoleWriter.cs
- src/D2L.Bmx/VirtualTerminal.cs
.NET's `Console.ForegroundColor` only targets stdout.
If we rely on `Console.ForegroundColor` and stdout is redirected (e.g. `bmx print | iex`), we won't get any colour on stderr either.
Related .NET issue: https://github.com/dotnet/runtime/issues/83146
Changing to use ANSI escape codes to control text colours to work around this issue.
---
depends on https://github.com/Brightspace/bmx/pull/464
> use ANSI escape codes to control colours of parameters we print

- src/D2L.Bmx/ConsoleWriter.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/UpdateChecker.cs
- src/D2L.Bmx/WriteHandler.cs
More consistent and better control over console text colours.
Notably, the update reminder banner has better sized background colour now.
Before:
After:
> use ANSI escape codes to control all console text colours

- src/D2L.Bmx/Aws/AwsCredsCache.cs
- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/Okta/OktaApi.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/Program.cs
Noticed some minor issues with user-facing messages.
https://desire2learn.atlassian.net/browse/VUL-403
> fix up & touch up user facing messages

- src/D2L.Bmx/AwsCredsCreator.cs
- src/D2L.Bmx/ParameterSource.cs
Because it's not a required parameter, I didn't think to include it in the new parameter printing behaviour.
However, on second thought, this is one of the most common sources of problems users have - they have long duration defined in some config file that isn't compatible with the account/role that they want to use.
> print duration when provided via config file or CLI arg

- src/D2L.Bmx/Aws/AwsCredsCache.cs
- src/D2L.Bmx/BmxConfigProvider.cs
- src/D2L.Bmx/Okta/OktaSessionStorage.cs
- src/D2L.Bmx/UpdateChecker.cs
- src/D2L.Bmx/UpdateHandler.cs
- src/D2L.Bmx/VirtualTerminal.cs
`OperatingSystem.Is*` methods are newer and more efficient. They are basically constants.
A very rough check suggests that, with these new methods, the native AOT trimmer/linker can even eliminate OS-specific dead code!
See https://github.com/dotnet/aspnetcore/issues/24653
> replace RuntimeInformation.IsOSPlatform with OperatingSystem.Is*

- src/D2L.Bmx/AwsCredsCreator.cs
Not a big deal and shouldn't affect any practical use cases, but at least for consistency sake, duration should be like other parameters - don't print if the `--non-interactive` flag is supplied on the command line.
> don't print duration if --non-interactive supplied

- src/D2L.Bmx/AwsCredsCreator.cs
- src/D2L.Bmx/Okta/Models/AuthenticateResponse.cs
- src/D2L.Bmx/Okta/OktaClient.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/PrintHandler.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/WriteHandler.cs
The original `OktaApi` class is stateful, i.e. it matters in what order you call its methods. This makes it hard to use & error prone.
I've split up its methods and different states into three different classes, so each one is stateless and has a smaller scope.
When & how you can transition from one state (unauthed) to another (authed) is also enforced via the API contract (rather than  relying on knowledge of its underlying behaviour).
https://desire2learn.atlassian.net/browse/VUL-104
> make Okta API client stateless

- src/D2L.Bmx/ConsoleWriter.cs
The update reminder's background area is misaligned on Windows:
This is because we didn't account for `\r` on Windows.
Still a mystery why this only happens with GitHub Actions' build but not with our local builds. Regardless, this fix works with both.
https://desire2learn.atlassian.net/browse/VUL-447
> trim each line when printing update reminder

- .github/workflows/publish.yml
Couldn't find the archive files because they were being created in those folders for each architecture
Made another test release to make sure it was working https://github.com/Brightspace/bmx/releases/tag/v3.1.3
VUL-71
> ci: fix build uploading after adding arm64

- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/ParameterDescriptions.cs
- src/D2L.Bmx/Program.cs
We're going to brand the new feature "passwordless" rather than "auto login".
Good to use consistent language everywhere.
https://desire2learn.atlassian.net/browse/VUL-522
> reword user-facing messages to say "passwordless"

- src/D2L.Bmx/OktaAuthenticator.cs
One nit I have about the current `OktaAuthenticator` class is that it puts DSSO and password auth at different abstraction levels.
This PR extracts password auth into its own dedicated private method, similar to DSSO auth.
The main public method now just shows the simple flow of "try cache -> try DSSO -> try password".
> extract password auth into a dedicated method

- src/D2L.Bmx/OktaAuthenticator.cs
If Okta redirects us to an unexpected page, we'd be stuck there waiting forever, because the current timeout logic is flawed.
> properly time out when waiting on the browser

- src/D2L.Bmx/Browser.cs
- src/D2L.Bmx/LoginHandler.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/ParameterDescriptions.cs
- src/D2L.Bmx/PrintHandler.cs
- src/D2L.Bmx/Program.cs
- src/D2L.Bmx/WriteHandler.cs
BMX inherently has to trust the org Okta domain name, so we decided it doesn't make too much sense to have an additional guard on an action that only visits the org Okta homepage.
There's also considerable less user friction and code complexity once the flag is removed.
https://desire2learn.atlassian.net/browse/VUL-506
> remove `--experimental-bypass-browser-security`

- .github/workflows/publish.yml
* We never published a release automatically, and I don't think we ever should.
We need to manually edit and review the release, and test the to-be-released binaries (as opposed to testing binaries built from another CI run or even locally).
So I've changed the workflow to keep (non-pre-)releases as draft.
* I'd like prereleases to all look like prereleases.
The current process doesn't enforce that you must include words like "preview", "beta" when you publish a prerelease. This can be confusing. I've made the workflow auto append "-preview-{datetime}" to the version/tag name for prereleases.
> tweak release workflow

- src/D2L.Bmx/BrowserLauncher.cs
- src/D2L.Bmx/OktaAuthenticator.cs
- src/D2L.Bmx/Program.cs
nit: such side-effect heavy and environment dependent operations should ideally not be static
> turn `Browser` non-static

- src/D2L.Bmx/OktaAuthenticator.cs
We have an overall timeout of 15 seconds for passwordless auth, but also we should not get stuck on a single page for anywhere near that long.
* https://github.com/Brightspace/bmx/pull/492/commits/253142f632cb13c986516480e760baf01d35086f pure refactor
* https://github.com/Brightspace/bmx/pull/492/commits/19d8da990e4f4becccbc1065271ba308f8429267 add per-page timeout
> add per-page timeout for passwordless auth

- src/D2L.Bmx/BrowserLauncher.cs
- src/D2L.Bmx/OktaAuthenticator.cs
Okta doesn't support DSSO on Linux anyway, and in my testing BMX always runs into the "unknown browser error" territory when I run it on Linux with Chrome installed.
Might as well remove the bloat and noise.
> don't try passwordless on Linux

- src/D2L.Bmx/ConsoleWriter.cs
- src/D2L.Bmx/D2L.Bmx.csproj
Avoid using hardcoded ANSI escape codes to make it more readable.
VUL-424
> Use spectre.console lib to manage ANSI escape code

- README.md
The info in my change is obvious to some folks, but I lost a good chunk of time to this and it seems like a straightforward addition.
Essentially when I read the readme I only saw a way to use profiles when invoking AWS through the CLI (`--profile` option), whereas my usage was inside Node scripts. I just wanted env var(s) I could set so that my Node scripts would work. I ended up trying to go the `bmx print` route but had lots of grief trying to do that.
I also thought the profile was a BMX concept and not AWS, which is my fault but hopefully this makes it clearer!
VOY-1
> Add AWS_PROFILE env var to readme
