Brightspace/bmx

.editorconfig, .gitignore, Bmx.CommandLine/Bmx.CommandLine.csproj, Bmx.CommandLine/CommandLine.cs, Bmx.CommandLine/Program.cs, Bmx.Core/Bmx.Core.csproj, Bmx.Core/BmxCore.cs, Bmx.Core/Events.cs, Bmx.Core/IIdentityProvider.cs, Bmx.Core/MfaType.cs, Bmx.Idp.Okta/Bmx.Idp.Okta.csproj, Bmx.Idp.Okta/OktaClient.cs, Bmx.Idp.Okta/models/AuthenticateChallengeMfaOptions.cs, Bmx.Idp.Okta/models/AuthenticateOptions.cs, Bmx.Idp.Okta/models/AuthenticationResponse.cs, Bmx.Idp.Okta/models/OktaError.cs, Bmx.Idp.Okta/models/OktaMfaFactor.cs, Bmx.Idp.Okta/models/Readme.md, Bmx.sln
For Inspiration June 2020.
Quick overview of reasoning:
Brings code more in line with D2L's core langs (increases chance this project can be maintained going forwards)
It's been through one rewrite to golang already (from python) for valid reasons, hopefully this is a equally valid reason as well.
==
Fairly large undertaking (LoC wise), will be split over a series of PRs into this dotnet branch prior to being placed on master.
PS: Will be creating a project under the projects tab to track further goals for release 2.1
=> Initial work for rewriting BMX in .NET Core

README.md
Updating the docs to configure and use bmx with aws
This was born out of notes I made during my own struggle to configure and use bmx.
Addition includes:
- pre-requisites to use bmx/aws-cli
- steps to setup bash alias to call bmx with required flags
- details on changing region while using bmx
- Verification of successful aws configuration
- sanity checks to confirm bmx is working correctly
=> Update BMX readme with more explicit setup steps

.github/workflows/editorconfig-checker.yml, .github/workflows/format.yml, D2L.Bmx.sln, src/D2L.Bmx/Authenticate.cs, src/D2L.Bmx/Program.cs
Adds format  and editorconfig-checker workflows
=> Adds format and editorconfig-checker workflows

src/D2L.Bmx/ConsolePrompter.cs
strings are immutable, and creating a new string on every keystroke is wasteful
=> optimize password input handling

.github/workflows/publish.yml
Couples typos lying around. After being able to run the workflow I found them all and should be sorted
=> ci: fix publish typos

.github/workflows/publish.yml, src/D2L.Bmx/BmxConfig.cs, src/D2L.Bmx/BmxConfigProvider.cs, src/D2L.Bmx/ConfigureHandler.cs, src/D2L.Bmx/ConsolePrompter.cs
It's a feature that gets used often
=> configure: add allow project config prompt

src/D2L.Bmx/BmxConfigProvider.cs, src/D2L.Bmx/Okta/OktaSessionStorage.cs
Update both session and config's permission to 600 on creation
=> Set user read/write permissions when creating files

src/D2L.Bmx/ConsolePrompter.cs, src/D2L.Bmx/Okta/OktaApi.cs, src/D2L.Bmx/Program.cs
To support Bmx with Okta preview.
=> Enable Inputing either org name or full domain 

src/D2L.Bmx/Program.cs
Having a full screen of unintelligible text dumped on the user is bad UX.
[Hide whitespace changes](https://github.com/Brightspace/bmx/pull/325/files?w=1)
=> don't show exception details to user

src/D2L.Bmx/AwsCredsCreator.cs, src/D2L.Bmx/BmxConfig.cs, src/D2L.Bmx/BmxConfigProvider.cs, src/D2L.Bmx/ConfigureHandler.cs, src/D2L.Bmx/ConsolePrompter.cs, src/D2L.Bmx/Program.cs
=> rename default_duration to duration in config

src/D2L.Bmx/Program.cs
Nit. This is clearer I think.
---
The diff may be best viewed on the command line with
```
git diff --color-moved=dimmed-zebra main separate-options
```
See Git docs on the diff options: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
=> group CLI options according to which command(s) they serve

src/D2L.Bmx/D2L.Bmx.csproj, src/D2L.Bmx/HtmlXmlHelper.cs
=> use proper HTML parsing to extract SAMLResponse

nuget.config, src/D2L.Bmx/Aws/AwsClient.cs, src/D2L.Bmx/AwsCredsCreator.cs, src/D2L.Bmx/ConfigureHandler.cs, src/D2L.Bmx/D2L.Bmx.csproj, src/D2L.Bmx/OktaAuthenticator.cs, src/D2L.Bmx/PrintHandler.cs, src/D2L.Bmx/WriteHandler.cs
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/primary-constructors
related discussion: https://d2l.slack.com/archives/G4P099831/p1687274202191849
=> use primary constructor

.github/workflows/publish.yml
easier to know when a change introduces significant bloat to the binary
=> check binary sizes in CI

src/D2L.Bmx/ConfigureHandler.cs, src/D2L.Bmx/Program.cs
Smooth out the install process a bit. 
https://trello.com/c/kKIKoUrM/1271-add-non-interactive-flag-to-bmx-configure
=> Noninteractive configure

src/D2L.Bmx/ConsolePrompter.cs
Noticed it when running configure command
=> fix spacing on org console prompt

src/D2L.Bmx/ConsolePrompter.cs
=> consistent casing for "optional"

src/D2L.Bmx/ConsolePrompter.cs
Noticed this feature gap when comparing with the Go version.
=> auto select account & role when only one is available

README.md
Putting this in README serves two purpose:
* Make the fact that there's a recent major release and its breaking changes more obvious and accessible. This is a common practice in many open source project.
* Serves as a draft for the release notes of our upcoming v3.0.0 release.
=> list notable changes between v2 & v3 on README

README.md
new people don't know what it means
=> clarify "account" in README

README.md
to prevent people from directly executing the commands without putting in the real values
=> update placeholder format in README.md

src/D2L.Bmx/Okta/OktaApi.cs, src/D2L.Bmx/OktaAuthenticator.cs
Trusting session cache and removing check with api
=> okta: removing /me check

src/D2L.Bmx/Program.cs
It's weird to say "you can update now!" when the user is literally updating.
=> disable auto update check when running the update command

src/D2L.Bmx/BmxPaths.cs, src/D2L.Bmx/Program.cs, src/D2L.Bmx/UpdateHandler.cs
avoid creating arbitrary directories in unexpected places on users' computers
https://d2l.slack.com/archives/G4P099831/p1704992370878349
=> use system temporary directory for update

src/D2L.Bmx/UpdateHandler.cs
=> include file path in update error message

src/D2L.Bmx/ConsolePrompter.cs
Now that I've found a better way to detect mintty specifically, we can use a more specific warning message (with colour!)
https://desire2learn.atlassian.net/browse/VUL-403
=> touch up mintty warning message

src/D2L.Bmx/VirtualTerminal.cs
winpty doesn't support ANSI escape sequences by default, so we can't treat mintty as supporting them unconditionally.
Before (with winpty):
After (both with and without winpty):
=> make coloured text work under winpty

src/D2L.Bmx/ConsolePrompter.cs
https://github.com/dotnet/runtime/issues/22314 is fixed in .NET 9, so we don't need these hacks now.
https://desire2learn.atlassian.net/browse/VUL-427
---
[hide whitespace changes](https://github.com/Brightspace/bmx/pull/476/files?w=1)
=> remove console IO hack

README.md
https://desire2learn.atlassian.net/browse/VUL-524
=> add passwordless auth section to README

src/D2L.Bmx/D2L.Bmx.csproj, src/D2L.Bmx/OktaAuthenticator.cs
https://desire2learn.atlassian.net/browse/VUL-626
=> add more debug logs for passwordless auth

src/D2L.Bmx/OktaAuthenticator.cs
Users see occasional timeouts on the first page load during passwordless auth.
The first page load is always cutting a bit too close to the timeout.
Good to increase the timeout to reduce random failures.
https://desire2learn.atlassian.net/browse/VUL-626
=> longer timeout for first page load during passwordless auth

.github/workflows/publish.yml, Dockerfile.al2, Dockerfile.alpine
https://desire2learn.atlassian.net/browse/VUL-648
=> build for Linux ARM64 in CI

.github/workflows/publish.yml
Mistakenly removed in https://github.com/Brightspace/bmx/pull/502
https://desire2learn.atlassian.net/browse/VUL-648
=> add back Version environment variable in CI

src/D2L.Bmx/MessageWriter.cs
Updating method from public to private
HOD-3557
=> update method to private
